In [79]:
from datetime import datetime
import pandas as pd
from geopy import distance
import numpy as np

import random

import pymongo
from pymongo import MongoClient

In [80]:
shapes = pd.read_csv('sfmta_2017-02-10/shapes.txt')
trips = pd.read_csv('sfmta_2017-02-10/trips.txt')
sched = pd.read_csv('stop_sequence.csv')
stops = pd.read_csv('sfmta_2017-02-10/stops.txt')

In [81]:
stops.head()

,stop_id,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url
0,98,2ND ST & MARKET ST,,37.789255,-122.401225,,
1,100,STEUART ST & FRANCISCO ST,,37.794463,-122.394607,,
2,202,COLUMBUS AVE & Pacific Ave,,37.797055,-122.405669,,
3,210,LINCOLN WAY & 19TH AVE,,37.765375,-122.477197,,
4,383,19TH AVE & LINCOLN WAY,,37.765375,-122.477197,,

In [82]:
client = MongoClient('localhost', 27017)

db = client['avl_pipeline_test']
trip_coll = db['trips']

In [83]:
sample_id = trip_coll.find_one({},{'_id':0, 'trip_id':1})['trip_id']
shape_id = trips[trips['trip_id'] == sample_id]['shape_id'].values[0]
trip_shape = shapes[shapes['shape_id'] == shape_id]

In [84]:
def get_dist(row, stop_tuple):
    shape_lat = float(row['shape_pt_lat'])
    shape_lon = float(row['shape_pt_lon'])
    return distance.distance((shape_lat, shape_lon), stop_tuple).m

In [85]:
stops_distances = []
stop_lat = []
stop_lon = []
stop_name = []

for idx, stp_srs in sched.iterrows():
    
    # Get the details of the stops
    stp_id = stp_srs['stop_id']
    stp_dtls = stops[stops['stop_id'] == stp_id]
    
    stp_lat = float(stp_dtls['stop_lat'])
    stp_lon = float(stp_dtls['stop_lon'])
    
    stop_lat.append(stp_lat)
    stop_lon.append(stp_lon)
    
    stop_name.append(stp_dtls['stop_name'].values[0])
    
    tups = (stp_lat, stp_lon)
    
    trip_shape['stop_dist'] = trip_shape.apply(lambda row: get_dist(row, tups), axis=1)
    
    closest_idx = trip_shape['stop_dist'].idxmin()
    
    stops_distances.append(trip_shape.loc[closest_idx]['shape_dist_traveled'])

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [86]:
sched['stop_distance'] = stops_distances
sched['stop_lat'] = stop_lat
sched['stop_lon'] = stop_lon
sched['stop_name'] = stop_name

In [87]:
stop_name

['Sacramento St & Cherry St',
 'California St & Maple St',
 'California St & Cherry St',
 'Arguello Blvd & California St',
 'Arguello Blvd & Clement St',
 'Arguello Blvd & Geary Blvd',
 'Arguello Blvd & Balboa St',
 'Fulton St & Arguello Blvd',
 'Stanyan St & Fulton St',
 'Stanyan St & Hayes St',
 'Haight St & Stanyan St',
 'Haight St & Clayton St',
 'Ashbury St & Waller St',
 'Ashbury St & Frederick St',
 'Ashbury St & Piedmont St',
 'Ashbury St & Clifford Ter',
 'ASHBURY ST & CLAYTON ST',
 'Clayton St & Twin Peaks Blvd',
 'Clayton St & Corbett Ave',
 'Clayton St & Market St',
 'Market St & Clayton St',
 '18th St & Danvers St',
 '18th St & Hattie St',
 '18th St & Diamond St',
 '18th St & Castro St',
 '18th St & Noe St',
 '18th St & Sanchez St',
 '18th St & Church St',
 '18th St & Dolores St',
 '18th St & Guerrero St',
 '18th St & Valencia St',
 'Mission St & 18th St',
 '16th St & Mission St',
 '16th St & Shotwell St',
 '16th St & Harrison St',
 '16th St & Bryant St',
 '16th St & Potrero Ave',
 'Potrero Ave & 17th St',
 'Potrero Ave & 18th St',
 'Potrero Ave & 20th St',
 'Sf General Hospital',
 'Potrero Ave & 23rd St',
 'Potrero Ave & 24th St',
 '25th St & Potrero Ave']

In [88]:
sched

,stop_id,stop_sequence,seq_str,stop_distance,stop_lat,stop_lon,stop_name
0,6293,1,1,0.0,37.786908,-122.456560,Sacramento St & Cherry St
1,3879,2,2,206.0,37.786248,-122.455207,California St & Maple St
2,3852,3,3,352.0,37.786042,-122.456835,California St & Cherry St
3,3644,4,4,575.0,37.785560,-122.459254,Arguello Blvd & California St
4,3645,5,5,852.0,37.783071,-122.459070,Arguello Blvd & Clement St
5,3649,6,6,1067.0,37.781429,-122.458955,Arguello Blvd & Geary Blvd
6,3642,7,7,1513.0,37.777075,-122.458645,Arguello Blvd & Balboa St
7,4224,8,8,1842.0,37.774282,-122.458003,Fulton St & Arguello Blvd
8,6479,9,9,2184.0,37.774604,-122.454714,Stanyan St & Fulton St
9,6481,10,10,2381.0,37.772766,-122.454335,Stanyan St & Hayes St
10,4963,11,11,2800.0,37.769170,-122.453075,Haight St & Stanyan St
11,4947,12,12,3242.0,37.769714,-122.448662,Haight St & Clayton St
12,3665,13,13,3494.0,37.769161,-122.446851,Ashbury St & Waller St
13,7295,14,14,3703.0,37.767305,-122.446473,Ashbury St & Frederick St
14,3663,15,15,3929.0,37.765298,-122.446072,Ashbury St & Piedmont St
15,3657,16,16,4049.0,37.764298,-122.446095,Ashbury St & Clifford Ter
16,7220,17,17,4233.0,37.763014,-122.446966,ASHBURY ST & CLAYTON ST
17,4070,18,18,4445.0,37.760863,-122.446485,Clayton St & Twin Peaks Blvd
18,4076,19,19,4726.0,37.758668,-122.445866,Clayton St & Corbett Ave
19,4080,20,20,4881.0,37.758222,-122.444319,Clayton St & Market St
20,5663,21,21,4959.0,37.758409,-122.444055,Market St & Clayton St
21,3328,22,22,5291.0,37.760240,-122.443490,18th St & Danvers St
22,3336,23,23,5507.0,37.760488,-122.440778,18th St & Hattie St
23,3329,24,24,5837.0,37.760702,-122.437294,18th St & Diamond St
24,3326,25,25,6030.0,37.760845,-122.434842,18th St & Castro St
25,3341,26,26,6225.0,37.760960,-122.432905,18th St & Noe St
26,3345,27,27,6421.0,37.761094,-122.430682,18th St & Sanchez St
27,3323,28,28,6617.0,37.761245,-122.428138,18th St & Church St
28,3331,29,29,6818.0,37.761388,-122.425927,18th St & Dolores St
29,3334,30,30,7019.0,37.761521,-122.423646,18th St & Guerrero St
30,3349,31,31,7216.0,37.761663,-122.421423,18th St & Valencia St
31,5553,32,32,7510.0,37.762635,-122.419348,Mission St & 18th St
32,3292,33,33,7771.0,37.765020,-122.419280,16th St & Mission St
33,3299,34,34,8061.0,37.765218,-122.416048,16th St & Shotwell St
34,3289,35,35,8350.0,37.765377,-122.413290,16th St & Harrison St
35,3282,36,36,8582.0,37.765595,-122.410408,16th St & Bryant St
36,3296,37,37,8842.0,37.765764,-122.407612,16th St & Potrero Ave
37,6029,38,38,8987.0,37.764434,-122.407475,Potrero Ave & 17th St
38,6031,39,39,9272.0,37.761640,-122.407290,Potrero Ave & 18th St
39,6033,40,40,9559.0,37.759080,-122.407050,Potrero Ave & 20th St
40,7809,42,42,10095.0,37.755208,-122.406667,Sf General Hospital
41,6037,43,43,10127.0,37.753990,-122.406570,Potrero Ave & 23rd St
42,6039,44,44,10269.0,37.752942,-122.406393,Potrero Ave & 24th St
43,3511,45,45,10494.0,37.751407,-122.406680,25th St & Potrero Ave

In [89]:
sched.to_csv('stop_seq_dist_latlon.csv', index=False)